version: 0.0
os: linux
files:
  - source: ./composer.*
    destination: /var/vhosts/framework.zend.com
  - source: ./config
    destination: /var/vhosts/framework.zend.com/config
  - source: ./data
    destination: /var/vhosts/framework.zend.com/data
  - source: ./public
    destination: /var/vhosts/framework.zend.com/public
  - source: ./src
    destination: /var/vhosts/framework.zend.com/src
  - source: ./templates
    destination: /var/vhosts/framework.zend.com/templates
hooks:
  ApplicationStop:
    - location: service nginx stop
      timeout: 300
      runas: root
  ApplicationStart:
    - location: service nginx start
      timeout: 300
      runas: root
  AfterInstall:
    - location: composer install --no-ansi --no-dev --no-interaction --no-progress --no-scripts --optimize-autoloader
      timeout: 600
    - location: php bin/build.php
      timeout: 300
    - location: php bin/stats.php
      timeout: 300
